### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by DanielMues** [DanielMues/Collector#5]
- [ ] show active icontypes
- [ ] implement first type buffs
- [ ] icons and type buffs for enemy
- [ ] placement of units just on your side of the field
- [ ] teamposition via scriptable object -> enemy
